config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :comments

      resources :goings

      resources :events

      resources :profiles
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "events#index"
  resources :comments
  resources :goings
  resources :events
  devise_for :profiles
  resources :profiles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/going.rb
class Going < ApplicationRecord
  # Direct associations

  belongs_to :event

  belongs_to :attendee,
             class_name: "Profile",
             foreign_key: "profile_id"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    attendee.to_s
  end
end

app/controllers/api/v1/goings_controller.rb
class Api::V1::GoingsController < Api::V1::GraphitiController
  def index
    goings = GoingResource.all(params)
    respond_with(goings)
  end

  def show
    going = GoingResource.find(params)
    respond_with(going)
  end

  def create
    going = GoingResource.build(params)

    if going.save
      render jsonapi: going, status: :created
    else
      render jsonapi_errors: going
    end
  end

  def update
    going = GoingResource.find(params)

    if going.update_attributes
      render jsonapi: going
    else
      render jsonapi_errors: going
    end
  end

  def destroy
    going = GoingResource.find(params)

    if going.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: going
    end
  end
end

app/controllers/goings_controller.rb
class GoingsController < ApplicationController
  before_action :set_going, only: %i[show edit update destroy]

  def index
    @q = Going.ransack(params[:q])
    @goings = @q.result(distinct: true).includes(:attendee,
                                                 :event).page(params[:page]).per(10)
  end

  def show; end

  def new
    @going = Going.new
  end

  def edit; end

  def create
    @going = Going.new(going_params)

    if @going.save
      message = "Going was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @going, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @going.update(going_params)
      redirect_to @going, notice: "Going was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @going.destroy
    message = "Going was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to goings_url, notice: message
    end
  end

  private

  def set_going
    @going = Going.find(params[:id])
  end

  def going_params
    params.require(:going).permit(:profile_id, :event_id)
  end
end

app/views/goings/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Going #<%= going.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Profile</dt>
      <dd>
        <% if @going.attendee.present? %>
          <%= link_to going.attendee, going.attendee %>
        <% end %>
      </dd>

      <dt>Event</dt>
      <dd>
        <% if @going.event.present? %>
          <%= link_to going.event, going.event %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back going, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_going_url(going), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to going, method: :delete, data: { confirm: "Do you really want to delete this going?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(going.updated_at) %> ago
  </div>
</div>

app/views/goings/_form.html.erb
<% was_validated = going.errors.any? %>

<%= form_with(model: going, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% profile_class = "form-control" %>
    <% profile_was_invalid = going.errors.include?(:profile) %>

    <% if was_validated %>
      <% if profile_was_invalid %>
        <% profile_class << " is-invalid" %>
      <% else %>
        <% profile_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :profile_id %>
    <%= f.collection_select :profile_id, Profile.all, :id, :to_s, {}, class: "form-control" %>
    <% if profile_was_invalid %>
      <% going.errors.full_messages_for(:profile).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% event_class = "form-control" %>
    <% event_was_invalid = going.errors.include?(:event) %>

    <% if was_validated %>
      <% if event_was_invalid %>
        <% event_class << " is-invalid" %>
      <% else %>
        <% event_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :event_id %>
    <%= f.collection_select :event_id, Event.all, :id, :to_s, {}, class: "form-control" %>
    <% if event_was_invalid %>
      <% going.errors.full_messages_for(:event).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/goings/_goings_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "goings_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :attendee_email_cont, "Attendee email contains" %>
    <%= f.text_field :attendee_email_cont, :class => "form-control", :placeholder => "Attendee email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/goings" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#goings_filters">
  Show filters
</a>

app/views/goings/_list_item.html.erb
<%= link_to going, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= going %>
    <small class="text-muted">
      <%= time_ago_in_words(going.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/goings/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Going #<%= @going.id %>
      </h2>

      <div class="card-body">
        <%= render "form", going: @going %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/goings/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Goings

      <%= link_to new_going_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "goings/goings_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Goings

        <%= link_to new_going_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @goings, partial: "list_item", as: :going %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @goings, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/goings/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Going
      </h2>

      <div class="card-body">
        <%= render "form", going: @going %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/goings/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @going, partial: "card", as: :going %>
  </div>
</div>