config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :comments

      resources :goings

      resources :events

      resources :profiles
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "events#index"
  resources :comments
  resources :goings
  resources :events
  devise_for :profiles
  resources :profiles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  # Direct associations

  has_many   :attendees,
             class_name: "Going",
             dependent: :destroy

  belongs_to :host,
             class_name: "Profile",
             foreign_key: "profile_id"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    host.to_s
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::GraphitiController
  def index
    events = EventResource.all(params)
    respond_with(events)
  end

  def show
    event = EventResource.find(params)
    respond_with(event)
  end

  def create
    event = EventResource.build(params)

    if event.save
      render jsonapi: event, status: :created
    else
      render jsonapi_errors: event
    end
  end

  def update
    event = EventResource.find(params)

    if event.update_attributes
      render jsonapi: event
    else
      render jsonapi_errors: event
    end
  end

  def destroy
    event = EventResource.find(params)

    if event.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: event
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :current_profile_must_be_event_host,
                only: %i[edit update destroy]

  before_action :set_event, only: %i[show edit update destroy]

  def index
    @q = Event.ransack(params[:q])
    @events = @q.result(distinct: true).includes(:host,
                                                 :attendees).page(params[:page]).per(10)
  end

  def show
    @going = Going.new
  end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = Event.new(event_params)

    if @event.save
      message = "Event was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @event, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    message = "Event was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to events_url, notice: message
    end
  end

  private

  def current_profile_must_be_event_host
    set_event
    unless current_profile == @event.host
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:profile_id, :date_time, :location,
                                  :details, :comments)
  end
end

app/views/events/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Event #<%= event.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Profile</dt>
      <dd>
        <% if @event.host.present? %>
          <%= link_to event.host, event.host %>
        <% end %>
      </dd>

      <dt>Date time</dt>
      <dd><%= event.date_time %></dd>

      <dt>Location</dt>
      <dd><%= event.location %></dd>

      <dt>Details</dt>
      <dd><%= event.details %></dd>

      <dt>Comments</dt>
      <dd><%= event.comments %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back event, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_profile == @event.host %>
          <%= link_to edit_event_url(event), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_profile == @event.host %>
          <%= link_to event, method: :delete, data: { confirm: "Do you really want to delete this event?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(event.updated_at) %> ago
  </div>
</div>

app/views/events/_event_attendees.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Attendees

    <a data-toggle="collapse" href="#event_attendees_new_form">
      Add going
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @event.attendees.each do |going| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to going, going %>

        <%= link_to going, method: :delete, data: { confirm: "Do you really want to delete this going" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="event_attendees_new_form">
        <%= render partial: "events/event_attendees_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/events/_event_attendees_new_form.html.erb
<%= form_with(model: @going, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :profile_id %>

    <%= f.collection_select :profile_id, Profile.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :event_id, value: @event.id %>

  <%= f.submit "Create going", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/events/_events_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "events_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :comments_cont, "Comments contains" %>
    <%= f.text_field :comments_cont, :class => "form-control", :placeholder => "Comments contains" %>
  </div>

  <div class="form-group">
    <%= f.label :details_cont, "Details contains" %>
    <%= f.text_field :details_cont, :class => "form-control", :placeholder => "Details contains" %>
  </div>

  <div class="form-group">
    <%= f.label :location_cont, "Location contains" %>
    <%= f.text_field :location_cont, :class => "form-control", :placeholder => "Location contains" %>
  </div>

  <div class="form-group">
    <%= f.label :date_time, "Date time" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='date_timegteqPicker' data-target-input="nearest">
          <%= f.text_field :date_time_gteq, :class => "form-control datetimepicker-input", :placeholder => "Date time greater than or equal to", :data => {:target => '#date_timegteqPicker'} %>
          <div class="input-group-append" data-target='#date_timegteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='date_timelteqPicker' data-target-input="nearest">
          <%= f.text_field :date_time_lteq, :class => "form-control datetimepicker-input", :placeholder => "Date time less than or equal to", :data => {:target => '#date_timelteqPicker'} %>
          <div class="input-group-append" data-target='#date_timelteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#date_timegteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#date_timelteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#date_timegteqPicker').on("dp.change", function (e) {
              $('#date_timelteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#date_timelteqPicker').on("dp.change", function (e) {
              $('#date_timegteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :host_email_cont, "Host email contains" %>
    <%= f.text_field :host_email_cont, :class => "form-control", :placeholder => "Host email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/events" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#events_filters">
  Show filters
</a>

app/views/events/_form.html.erb
<% was_validated = event.errors.any? %>

<%= form_with(model: event, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.hidden_field :profile_id, value: current_profile.id %>
  <div class="form-group">
    <% date_time_class = "form-control" %>
    <% date_time_was_invalid = event.errors.include?(:date_time) %>

    <% if was_validated %>
      <% if date_time_was_invalid %>
        <% date_time_class << " is-invalid" %>
      <% else %>
        <% date_time_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :date_time %>
    <%= f.datetime_select :date_time, class: date_time_class, placeholder: "Enter date time" %>
    <% if date_time_was_invalid %>
      <% event.errors.full_messages_for(:date_time).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% location_class = "form-control" %>
    <% location_was_invalid = event.errors.include?(:location) %>

    <% if was_validated %>
      <% if location_was_invalid %>
        <% location_class << " is-invalid" %>
      <% else %>
        <% location_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :location %>
    <%= f.text_field :location, class: location_class, placeholder: "Enter location" %>
    <% if location_was_invalid %>
      <% event.errors.full_messages_for(:location).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% detail_class = "form-control" %>
    <% detail_was_invalid = event.errors.include?(:detail) %>

    <% if was_validated %>
      <% if detail_was_invalid %>
        <% detail_class << " is-invalid" %>
      <% else %>
        <% detail_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :details %>
    <%= f.text_field :details, class: detail_class, placeholder: "Enter detail" %>
    <% if detail_was_invalid %>
      <% event.errors.full_messages_for(:detail).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% comment_class = "form-control" %>
    <% comment_was_invalid = event.errors.include?(:comment) %>

    <% if was_validated %>
      <% if comment_was_invalid %>
        <% comment_class << " is-invalid" %>
      <% else %>
        <% comment_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :comments %>
    <%= f.text_field :comments, class: comment_class, placeholder: "Enter comment" %>
    <% if comment_was_invalid %>
      <% event.errors.full_messages_for(:comment).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/events/_list_item.html.erb
<%= link_to event, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= event %>
    <small class="text-muted">
      <%= time_ago_in_words(event.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/events/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Event #<%= @event.id %>
      </h2>

      <div class="card-body">
        <%= render "form", event: @event %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Events

      <%= link_to new_event_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "events/events_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Events

        <%= link_to new_event_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @events, partial: "list_item", as: :event %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @events, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Event
      </h2>

      <div class="card-body">
        <%= render "form", event: @event %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @event, partial: "card", as: :event %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "events/event_attendees" %>
  </div>
</div>